### ISSUE TITLE
Was TLS 1.3 Early Data support ever integrated into any popular clients that also support HTTP/2?

### ISSUE THREAD

**Issue by LaRuim** [martinthomson/h2-0rtt#3]
Clients such as cURL and nghttp support HTTP/2, but I can't find a way to send TLS 1.3 Early Data with them. 

OpenSSL s_client allows for TLS 1.3 Early Data being sent, but it seems to fail when I try and pass manually crafted frames (with the Preface) as an early data request while setting the alpn as h2; although that same manually crafted set of frames seems to be well received by the server when sending it after a 1RTT handshake with h2 alpn negotiated, however s_client seems to terminate the connection before even receiving a response.

**Comment by martinthomson** [comment]
Most (all?) browser clients support early data with HTTP/2.  What this draft aims to do is make it possible to use HTTP/2 *extensions* with early data in a coherent fashion.  You would have to ask the developers of other tools about what their support looks like.  In some cases, those tools are more conservative about this feature because of the higher risk of unanticipated problems.

**Comment by LaRuim** [comment]
Thanks for the information!
